CREATE TABLE USER_DETAILS(USERNAME VARCHAR2(20),
DISPLAY_NAME VARCHAR2(20) UNIQUE,
USER_PASSWORD VARCHAR2(20) NOT NULL,
PRIMARY KEY(USERNAME));

Select * from USER_DETAILS;

CREATE OR REPLACE TRIGGER SET_DEFUALT_SETTINGS
AFTER INSERT ON USER_DETAILS
FOR EACH ROW
BEGIN
    INSERT INTO SETTINGS(USERNAME, SETTING_NAME, SETTING_VALUE) VALUES(:NEW.USERNAME,'THEME','METAL');
END;
/
CREATE TABLE SETTINGS( USERNAME VARCHAR(20) REFERENCES USER_DETAILS(USERNAME) ON DELETE CASCADE NOT NULL,
SETTING_NAME VARCHAR2(30) NOT NULL,
 SETTING_VALUE VARCHAR(20) CHECK(SETTING_VALUE IN('FALSE','TRUE','LIGHT','DARK','METAL')),
PRIMARY KEY(USERNAME,SETTING_NAME));
select * from settings;



CREATE OR REPLACE TRIGGER AUTO_FILL_LOG
AFTER INSERT ON USER_DETAILS
FOR EACH ROW
BEGIN
    INSERT INTO LOG_STATUS VALUES(:NEW.USERNAME,'LOGGED OUT',DEFAULT);
END;
/
CREATE TABLE LOG_STATUS(USERNAME VARCHAR2(20) REFERENCES USER_DETAILS(USERNAME) ON DELETE CASCADE NOT NULL,
STATUS VARCHAR2(20) CHECK(STATUS IN('LOGGED IN','LOGGED OUT')),
TIMES TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(USERNAME,STATUS,TIMES));
select * from log_status;

CREATE TABLE CONTACTS(USERNAME VARCHAR2(20) REFERENCES USER_DETAILS(USERNAME) ON DELETE CASCADE NOT NULL,
CONTACT_NAME VARCHAR(20),CONTACT_IP VARCHAR2(20),TIMES TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
PRIMARY KEY(USERNAME,CONTACT_NAME,CONTACT_IP));

SELECT * FROM HR.USER_DETAILS;
SELECT * FROM HR.SETTINGS;
SELECT * FROM HR.LOG_STATUS;
SELECT * FROM CONTACTS;

DELETE FROM HR.LOG_STATUS;
DELETE FROM HR.SETTINGS;
DELETE FROM HR.USER_DETAILS;
DELETE FROM CONTACTS;
drop table user_details;
drop table log_status;
drop table settings;
DROP TABLE CONTACTS;
COMMIT;
