CREATE TABLE USER_DETAILS(TOKEN NUMBER,
USERNAME VARCHAR2(20) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(20) NOT NULL,
PRIMARY KEY(TOKEN,USERNAME));
CREATE SEQUENCE user_token_seq START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER user_details_token_bir
BEFORE INSERT ON USER_DETAILS
FOR EACH ROW
BEGIN
    SELECT user_token_seq.NEXTVAL INTO :NEW.TOKEN FROM DUAL;
END;
/


Select * from USER_DETAILS;

CREATE TABLE SETTINGS( USERNAME VARCHAR(20) REFERENCES USER_DETAILS(USERNAME) ON DELETE CASCADE NOT NULL,
SETTING_NAME VARCHAR2(30) NOT NULL,
 SETTING_VALUE VARCHAR(20) CHECK(SETTING_VALUE IN('FALSE','TRUE')),
PRIMARY KEY(USERNAME,SETTING_NAME));
select * from settings;

CREATE OR REPLACE TRIGGER SET_DEFUALT_SETTINGS
AFTER INSERT ON USER_DETAILS
FOR EACH ROW
BEGIN
    INSERT INTO SETTINGS(USERNAME, SETTING_NAME, SETTING_VALUE) VALUES(:NEW.USERNAME,'KEEP LOGGED IN','FALSE');
END;
/
CREATE TABLE LOG_STATUS(USERNAME VARCHAR2(20) REFERENCES USER_DETAILS(USERNAME) ON DELETE CASCADE NOT NULL,
STATUS VARCHAR2(20) CHECK(STATUS IN('LOGGED IN','LOGGED OUT')),
PRIMARY KEY(USERNAME,STATUS));
select * from log_status;

SELECT * FROM HR.USER_DETAILS;
SELECT * FROM HR.SETTINGS;
SELECT * FROM HR.LOG_STATUS;

DELETE FROM HR.LOG_STATUS;
DELETE FROM HR.SETTINGS;
DELETE FROM HR.USER_DETAILS;
COMMIT;

